package Cognizant.Number;

import java.util.Arrays;

/**
 * 📝 Problem: Special Sequence Generator
 *
 * Problem Statement:
 * You are given the first six terms of a sequence. Starting from the 7th term,
 * each new term is generated by adding the two most recent terms.
 * Return an array representing the first N terms of the sequence.
 *
 * Input Specification:
 * input1 : An integer value N
 * input2 : An integer array S of size 6
 *
 * Output Specification:
 * Return an integer array of size N.
 */
public class SequenceGenerator {

    public static int[] generateSequence(int N, int[] arr) {

        // N size er notun ekta array baniye ne
        int[] result = new int[N];

        // Tor logic ekhane likh...
        // Step 1: Prothom 6-ta element array 'S' theke 'result'-e copy kor.
        // (Ekta simple for loop chaliye, result[i] = S[i] kore de)
        for (int i = 0; i< arr.length ; i++){
            result[i] = arr[i];
        }

        // Step 2: Notun loop chala Index 6 theke (i = 6) N obdi.
        // Bhetore formula hobe: result[i] = result[i-1] + result[i-2];
        for (int i = arr.length ; i<result.length ; i++){
            result[i] = result[i-1]+result[i-2];
        }


        return result;
    }

    public static void main(String[] args) {
        // Test Case 1 (From Image)
        int input1 = 10;
        int[] input2 = {1, 2, 3, 4, 5, 6};

        System.out.println("--- Test Case 1 ---");
        System.out.println("Input N: " + input1);
        System.out.println("Input S: " + Arrays.toString(input2));

        int[] output = generateSequence(input1, input2);
        System.out.println("Output : " + Arrays.toString(output));
        // Expected Output: [1, 2, 3, 4, 5, 6, 11, 17, 28, 45]
    }
}